In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
# Implementation of the Backpropagation using keras
# Regression based problem
# Author: Muhammad Humayun Khan

df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns = ['cgpa','profile_score','salary'])
df

cgpa  profile_score  salary
0     8              8       4
1     7              9       5
2     6             10       6
3     5             12       7

In [4]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,InputLayer

In [7]:
model = Sequential()

model.add(InputLayer(shape=(2,)))
model.add(Dense(2, activation='linear'))
model.add(Dense(1, activation='linear'))

In [8]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
# randomly initialize weights
model.get_weights()

[array([[ 0.0068326 ,  0.9748379 ],
        [-0.36213905,  0.7702509 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.523744],
        [-1.333506]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype = np.float32),
              np.array([0.,0.], dtype=np.float32),
              np.array([[0.1],
                       [0.1]],dtype=np.float32),
              np.array([0.],dtype=np.float32)]

In [12]:
model.set_weights(new_weights)

In [13]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [14]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'mean_squared_error',optimizer = optimizer)

In [16]:
model.fit(df.iloc[:,0:-1].values,df['salary'].values,epochs = 75,verbose = 1, batch_size = 1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20.9877 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 27.4345 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28.6573 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.9815 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19.4366
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21.6582 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.1545 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20.6738 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25.9566 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.1322 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20.9712 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24.2336 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21.8041 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15.7735
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21.6316 
Epoch 16/75
4/4 ━━━━━

In [17]:
# change made by keras in weights
model.get_weights()

[array([[0.38233548, 0.38233548],
        [0.37919044, 0.37919044]], dtype=float32),
 array([0.2840438, 0.2840438], dtype=float32),
 array([[0.38495654],
        [0.38495654]], dtype=float32),
 array([0.21143608], dtype=float32)]